### ISSUE TITLE
Java 11 Compatibility check: jsp-api

### ISSUE THREAD

**Issue by ChrisTTPSC** [eclipse-ee4j/jsp-api#87]
Hi,
Could you help me by answering the following questions about jsp-api library:

Is the library compatible with Java 11 ? (Y/N)
Is the library supported with Java 11? (Y/N)
(If “N” in compatibility or support) What is the version that would be compatible and Supported?
Date of support availability?
Thanks

**Comment by bpcrao** [comment]
I am not contributor but I dont think is compatible

**Comment by markt-asf** [comment]
The jsp-api library is compatible with Java 11 (and 12).
The jsp-api library is supported with Java 11 (and 12). It is supported in the sense that if something doesn't work and you open a bug it won't get immediately rejected because you are using Java 11 (or 12).

Note that this only applies to the jsp-api library. There are multiple implementations of the JSP API and the answers to the above questions are likely to be different for each implementation.
